### ISSUE TITLE
Push all branches, not just master

### ISSUE THREAD

**Issue by ElijahLynn** [pantheon-systems/terminus-site-clone-plugin#9]
Just ran a `terminus site:clone` and it worked well without issues. However, it doesn't bring over old branches, which I have to manually do.

**Comment by ElijahLynn** [comment]
I see it is cloning all branches, but just pushing 1 branch, changed title. 

https://github.com/pantheon-systems/terminus-site-clone-plugin/blob/master/src/Commands/SiteCloneCommand.php#L481

**Comment by ataylorme** [comment]
@ElijahLynn I'll wait for your feedback in #11, though having all branches available may serve a different use case. My concern would be blowing away branches on the destination site with those on the source site if the same branch names, e.g. `master`, exist in both.

**Comment by ataylorme** [comment]
This is now _mostlyz_ covered in the [create new site and clone all environments example script](https://github.com/pantheon-systems/terminus-site-clone-plugin/tree/master/examples/create-new-site-and-clone-all-envs). I say mostly because only branches with a multidev are copied but that should suffice for most use cases. If another branch is needed then it can be manually pushed from the source site to the destination site using two git remotes.
